sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t invicit/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true invicit/react-test npm test -- --coverage

after_success:
    - docker build -t invicit/multi-client ./client
    - docker build -t invicit/multi-nginx ./nginx
    - docker build -t invicit/multi-server ./server
    - docker build -t invicit/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push invicit/multi-client
    - docker push invicit/multi-nginx
    - docker push invicit/multi-server
    - docker push invicit/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-eu-west-1-652818274405"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY